--- 
before_script: 
  - "node --version"
  - "npm --version"
  - "node_modules/.bin/newman --version"
install: 
  - "npm install newman"
language: node_js
node_js: 
  - "12.13.0"
script: 
  - "node_modules/.bin/newman run collection.json -e environment.json -g globals.json"