name: PostmanTests

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
    - main

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          collection: workflow.json
          reporters: cli
