# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    newman:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
            - uses: actions/checkout@main
            - uses: actions/setup-node@main
              with:
                node-version: '12'
                collection: workflow.json
                reporters: cli,htmlextra
            - name: install
            - run: npm install -g newman
            - run: npm install -g newman-reporter-htmlextra
            - run: npm install -g newman-reporter-testrail
            - run: newman run workflow.json  --reporters cli,htmlextra,testrail --reporter-htmlextra-export Report.html
            - name: Archive code coverage results
            - uses: actions/upload-artifact@main
              with:
                name: test-report
                path: output/Report.html
