# This is a basic workflow to help you get started with Actions
name: Newman Test Run
on:
  push:
    branches:
    - master
    
jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: '12'
          collection: workflow.json
      - run: npm install -g newman
      - run: newman run workflow.json
